version: "3.5"
services:
  app:
    build: .
    container_name: kreacity_app
    env_file: .env
    image: kreacity_app
    networks:
      - kreacity
    volumes:
    - ./src:/app/src
  nginx:
    container_name: kreacity_nginx
    image: nginx:alpine
    logging:
      driver: none
    networks:
      - kreacity
    ports:
      - 80:80
    volumes:
      - ./extra/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  kreacity:
    name: kreacity_network
    driver: bridge
