version: "3.5"
services:
  app:
    build: .
    container_name: kreacity_app
    env_file: .env
    image: kreacity_app
    networks:
      - kreacity
    volumes:
    - ./src:/app/src

  nginx:
    container_name: kreacity_nginx
    image: nginx:alpine
    logging:
      driver: none
    networks:
      - kreacity
    ports:
      - 80:80
    volumes:
      - ./extra/nginx/nginx.conf:/etc/nginx/nginx.conf

  mongo:
    container_name: kreacity_mongo
    environment:
      TZ: America/Bogota
      MONGO_INITDB_ROOT_USERNAME: kreacity_root
      MONGO_INITDB_ROOT_PASSWORD: kreacity_pass
    image: mongo:3-xenial
    networks:
      - kreacity
    ports:
      - 27017:27017
    volumes:
    - /tmp/data:/data/db

networks:
  kreacity:
    name: kreacity_network
    driver: bridge
